export const ActionTypes = {
    CREATE_REWORK: 'CREATE_REWORK',
    UPDATE_REWORK: 'UPDATE_REWORK',
    DELETE_REWORK: 'DELETE_REWORK',
    FETCH_REWORK: 'FETCH_REWORK',
    FETCH_REWORKS: 'FETCH_REWORKS',
    FETCH_REWORKS_BY_LOT: 'FETCH_REWORKS_BY_LOT',
    ERROR: 'ERROR',
    CLEAN_UP: 'CLEAN_UP',
}