export const ActionTypes = {
    CREATE_REGION: 'CREATE_REGION',
    UPDATE_REGION: 'UPDATE_REGION',
    DELETE_REGION: 'DELETE_REGION',
    FETCH_REGION: 'FETCH_REGION',
    FETCH_REGIONS: 'FETCH_REGIONS',
    ERROR: 'ERROR',
}