export const ActionTypes = {
    CREATE_BATCH: 'CREATE_BATCH',
    UPDATE_BATCH: 'UPDATE_BATCH',
    DELETE_BATCH: 'DELETE_BATCH',
    FETCH_BATCH: 'FETCH_BATCH',
    FETCH_BATCHES: 'FETCH_BATCHES',
    FETCH_BATCHES_BY_REGION: 'FETCH_BATCHES_BY_REGION',
    ERROR: 'ERROR',

}