export const ActionTypes = {
    CREATE_VARIABLE: 'CREATE_VARIABLE',
    UPDATE_VARIABLE: 'UPDATE_VARIABLE',
    DELETE_VARIABLE: 'DELETE_VARIABLE',
    FETCH_VARIABLE: 'FETCH_VARIABLE',
    FETCH_VARIABLES: 'FETCH_VARIABLES',
    ERROR: 'ERROR',
}