export const ActionTypes = {
    CREATE_LOT: 'CREATE_LOT',
    UPDATE_LOT: 'UPDATE_LOT',
    DELETE_LOT: 'DELETE_LOT',
    FETCH_LOT: 'FETCH_LOT',
    FETCH_LOTS: 'FETCH_LOTS',
    FETCH_LOTS_BY_BATCH: 'FETCH_LOTS_BY_BATCH',
    ERROR: 'ERROR',
    CLEAN_UP: 'CLEAN_UP',
}