export const ActionTypes = {
    CREATE_WAREHOUSE: 'CREATE_WAREHOUSE',
    UPDATE_WAREHOUSE: 'UPDATE_WAREHOUSE',
    DELETE_WAREHOUSE: 'DELETE_WAREHOUSE',
    FETCH_WAREHOUSE: 'FETCH_WAREHOUSE',
    FETCH_WAREHOUSES: 'FETCH_WAREHOUSES',
    FETCH_WAREHOUSES_BY_STYLE: 'FETCH_WAREHOUSES_BY_STYLE',
    FETCH_WAREHOUSES_BY_LOT: 'FETCH_WAREHOUSES_BY_LOT',
    ERROR: 'ERROR',
    CLEAN_UP: 'CLEAN_UP',
}