export const ActionTypes = {
    CREATE_ZONE: 'CREATE_ZONE',
    UPDATE_ZONE: 'UPDATE_ZONE',
    DELETE_ZONE: 'DELETE_ZONE',
    FETCH_ZONE: 'FETCH_ZONE',
    FETCH_ZONES: 'FETCH_ZONES',
    FETCH_ZONES_BY_STYLE: 'FETCH_ZONES_BY_STYLE',
    FETCH_ZONES_BY_LOT: 'FETCH_ZONES_BY_LOT',
    ERROR: 'ERROR',
    CLEAN_UP: 'CLEAN_UP'
}