export const ActionTypes = {
    CREATE_REPORT: 'CREATE_REPORT',
    FETCH_REPORT: 'FETCH_REPORT',
    FETCH_STYLE_REPORT: 'FETCH_STYLE_REPORT',
    FETCH_REPORT_BY_MONTH_AND_YEAR: 'FETCH_REPORT_BY_MONTH_AND_YEAR',
    FETCH_STYLE_REPORT_BY_MONTH_AND_YEAR: 'FETCH_STYLE_REPORT_BY_MONTH_AND_YEAR',
    ERROR: 'ERROR',
    CLEAN_UP: 'CLEAN_UP',
}