export const ActionTypes = {
    CREATE_COMMENT: 'CREATE_COMMENT',
    UPDATE_COMMENT: 'UPDATE_COMMENT',
    DELETE_COMMENT: 'DELETE_COMMENT',
    FETCH_COMMENT: 'FETCH_COMMENT',
    FETCH_COMMENTS: 'FETCH_COMMENTS',
    ERROR: 'ERROR',
    CLEAN_UP: 'CLEAN_UP',
}