export const ActionTypes = {
    CREATE_SALE: 'CREATE_SALE',
    UPDATE_SALE: 'UPDATE_SALE',
    DELETE_SALE: 'DELETE_SALE',
    FETCH_SALE: 'FETCH_SALE',
    FETCH_SALES: 'FETCH_SALES',
    FETCH_SALES_BY_LOT: 'FETCH_SALES_BY_LOT',
    FETCH_SALES_BY_STYLE: 'FETCH_SALES_BY_STYLE',
    ERROR: 'ERROR',
    CLEAN_UP: 'CLEAN_UP',
}