export const ActionTypes = {
    CREATE_STYLE: 'CREATE_STYLE',
    UPDATE_STYLE: 'UPDATE_STYLE',
    DELETE_STYLE: 'DELETE_STYLE',
    FETCH_STYLE: 'FETCH_STYLE',
    FETCH_STYLES: 'FETCH_STYLES',
    ERROR: 'ERROR',
}